SWP\Bundle\ContentBundle\Model\Article:
    type: mappedSuperclass
    table: swp_article
    repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ORM\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        slug:
            type: string
        body:
            type: text
        title:
            type: string
        lead:
            type: text
            nullable: true
        templateName:
            type: string
            nullable: true
        locale:
            type: string
        status:
            type: string
        extra:
            type: array
            options:
                default: 'a:0:{}'
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        mediaUpdatedAt:
            type: datetime
            nullable: true
        deletedAt:
            type: datetime
            nullable: true
        publishStartDate:
            type: date
            nullable: true
        publishEndDate:
            type: date
            nullable: true
        publishedAt:
            type: datetime
            nullable: true
        isPublishable:
            type: boolean
        metadata:
            type: json_array
            nullable: true
        code:
            type: string
    manyToOne:
        route:
            targetEntity: SWP\Bundle\ContentBundle\Model\RouteInterface
            inversedBy: articles
            fetch: "EAGER"
            joinColumn:
                name: route_id
                referencedColumnName: id
                onDelete: "SET NULL"
        featureMedia:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleMediaInterface
            fetch: "EAGER"
            cascade: ["persist"]
            joinColumn:
                name: feature_media
                referencedColumnName: id
                onDelete: "SET NULL"
        seoMetadata:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleSeoMetadataInterface
            joinColumn:
                name: seo_metadata_id
                referencedColumnName: id
            cascade: ['all']
    oneToMany:
        media:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleMediaInterface
            mappedBy: article
            cascade: ["remove"]
        sources:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleSourceReference
            mappedBy: article
            cascade: ["remove", "persist"]
        slideshows:
            targetEntity: SWP\Bundle\ContentBundle\Model\SlideshowInterface
            mappedBy: article
            fetch: "EAGER"
            cascade: ["all"]
            orphanRemoval: true
        relatedArticles:
            targetEntity: SWP\Bundle\ContentBundle\Model\RelatedArticleInterface
            mappedBy: relatesTo
            cascade: ["all"]
            orphanRemoval: true
    manyToMany:
        authors:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleAuthorInterface
            cascade: ["all"]
            joinTable:
                name: swp_article_author
                joinColumns:
                    article_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
                inverseJoinColumns:
                    author_id:
                        referencedColumnName: id
                        onDelete: "CASCADE"
        keywords:
            targetEntity: SWP\Bundle\ContentBundle\Model\KeywordInterface
            cascade: ["all"]
            joinTable:
                name: swp_article_keyword
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    keyword_id:
                        referencedColumnName: id
