SWP\Bundle\ContentBundle\Doctrine\ORM\Article:
    type: entity
    table: swp_article
    repositoryClass: SWP\Bundle\ContentBundle\Doctrine\ORM\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        slug:
            type: string
        body:
            type: text
        title:
            type: string
        lead:
            type: text
            nullable: true
        templateName:
            type: string
            nullable: true
        locale:
            type: string
        status:
            type: string
        createdAt:
            type: date
        updatedAt:
            type: date
            nullable: true
        deletedAt:
            type: date
            nullable: true
        publishStartDate:
            type: date
            nullable: true
        publishEndDate:
            type: date
            nullable: true
        publishedAt:
            type: date
            nullable: true
        isPublishable:
            type: boolean
        metadata:
            type: text
            nullable: true
        tenantCode:
            type: string
    uniqueConstraints:
        swp_article_slug_idx:
          columns: [ slug ]
    manyToOne:
        route:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\Route
            inversedBy: articles
            fetch: "EAGER"
            joinColumn:
                name: route_id
                referencedColumnName: id
                onDelete: "SET NULL"
    oneToMany:
        media:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\ArticleMedia
            mappedBy: article
            cascade: ["remove"]
