SWP\Bundle\ContentBundle\Model\SlideshowItem:
    type: mappedSuperclass
    table: swp_slideshow_item
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    fields:
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
             type: datetime
             nullable: true
    manyToOne:
        articleMedia:
            targetEntity: SWP\Bundle\ContentBundle\Model\ArticleMediaInterface
            cascade: ["remove"]
            orphanRemoval: true
            joinColumn:
                name: article_media_id
                referencedColumnName: id
                nullable: false
                onDelete: "SET NULL"

        slideshow:
            targetEntity: SWP\Bundle\ContentBundle\Model\SlideshowInterface
            cascade: ["all"]
            inversedBy: items
            joinColumn:
                name: slideshow_id
                referencedColumnName: id
                onDelete: CASCADE
                nullable: false
