SWP\Component\Rule\Model\Rule:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: string
        value:
            expose: true
            type: string
        priority:
            expose: true
            type: integer
        configuration:
            expose: true
            type: array
