lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem'
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase:      '%JWT_PASS_PHRASE%'
    token_ttl:        3600

services:
    acme_api.event.jwt_created_listener:
        class: SWP\Bundle\CoreBundle\EventListener\JWTCreatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }
