language: php

sudo: false

services:
  - redis-server

php:
  - 7.0
  - 7.1
  - nightly

env:
  global:
    - SYMFONY_ENV="test"
  matrix:
   - DOCTRINE_CACHE_DRIVER="redis" COMPOSER_FLAGS='update --prefer-stable'
   - DOCTRINE_CACHE_DRIVER="redis" COMPOSER_FLAGS='install'
   - DOCTRINE_CACHE_DRIVER="array" COMPOSER_FLAGS='update --prefer-stable'
   - DOCTRINE_CACHE_DRIVER="array" COMPOSER_FLAGS='install'

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'extension="redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini|grep redis
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv rehash
  - composer $COMPOSER_FLAGS --no-interaction --prefer-dist

script:
  - bin/phpspec run
  - bin/phpunit -c app/
  - cd src/SWP/Bundle/BridgeBundle && composer install --no-interaction --prefer-dist --ignore-platform-reqs && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/TemplatesSystemBundle && composer install --no-interaction --prefer-dist --ignore-platform-reqs && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/ContentBundle && composer install --no-interaction --prefer-dist --ignore-platform-reqs && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/SettingsBundle && composer install --no-interaction --prefer-dist --ignore-platform-reqs && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/UserBundle && composer install --no-interaction --prefer-dist --ignore-platform-reqs && bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
