language: php

dist: trusty
sudo: required

services:
  - redis-server

php:
  - 7.1
  - 7.2
  - nightly

env:
  global:
    - SYMFONY_ENV="test"
    - ES_VERSION=5.4.0 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.deb
  matrix:
   - DOCTRINE_CACHE_DRIVER="redis" COMPOSER_FLAGS='update --prefer-stable'
   - DOCTRINE_CACHE_DRIVER="redis" COMPOSER_FLAGS='install'
   - DOCTRINE_CACHE_DRIVER="array" COMPOSER_FLAGS='update --prefer-stable'
   - DOCTRINE_CACHE_DRIVER="array" COMPOSER_FLAGS='install'

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_install:
  - sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=4096
  - sudo /sbin/mkswap /var/swap.1
  - sudo /sbin/swapon /var/swap.1
  - sudo sysctl -w vm.max_map_count=262144
  - sudo sysctl -p
  - npm install -g json-server
  - sudo apt-get install supervisor

install:
  - wget ${ES_DOWNLOAD_URL}
  - sudo dpkg -i --force-confnew elasticsearch-${ES_VERSION}.deb
  - sudo service elasticsearch restart


before_script:
  - nohup json-server --watch src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/db.json --routes=src/SWP/Bundle/CoreBundle/Tests/Functional/Resources/routes.json &
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'extension="redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - cat ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini|grep redis
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - phpenv rehash
  - composer $COMPOSER_FLAGS --no-interaction --prefer-dist
  - php app/console rabbitmq-supervisor:build --env=test
  - php app/console rabbitmq-supervisor:control start --env=test

script:
  - bin/behat -f progress
  - bin/phpspec run
  - bin/phpunit -c app/
  - bin/phpunit --stderr -c app/ src/SWP/Bundle/CoreBundle/Tests/Security/Storage/DynamicDomainSessionStorageTest.php
  - cd src/SWP/Bundle/BridgeBundle && composer $COMPOSER_FLAGS --no-interaction --prefer-dist && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/TemplatesSystemBundle && composer $COMPOSER_FLAGS --no-interaction --prefer-dist && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/ContentBundle && composer $COMPOSER_FLAGS --no-interaction --prefer-dist && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/SettingsBundle && composer $COMPOSER_FLAGS --no-interaction --prefer-dist && bin/phpunit
  - cd ../../../../
  - cd src/SWP/Bundle/UserBundle && composer $COMPOSER_FLAGS --no-interaction --prefer-dist && bin/phpunit

cache:
  directories:
    - "node_modules"
    - $HOME/.composer/cache
