language: php
php:
  - 5.6
  - 5.5
  - nightly

before_script:
  - composer install

script:
  - bin/phpspec run
  - phpunit -c app/

notifications:
  hipchat:
    rooms:
      secure: dqqpZkkSZJgI0LECgv+cOCeqqMYobCGUJeD9GNXWvlyDQM9QoHisj55Pqlcp8cZLQgBMVPmG2frFGuPJDaehZgy9ymxQGPmsJfR73ybsLZ4kP8tP/d3boiBRApTU9qCzXvzVg0d29I5mKinjHZyvY4qw+qyffzQBkWaGf7yLOuZ9jaOkjxp0znfn33wEaY1pZSDjNYDwKuYwPPGCRqLrEIDYAIyiwegW+oLinJuqDF6B64HhXu6c8pjEwL4tLH4Rl+MzGQQE8J4nZHbJZ4fsaC8zdB+f5oStS6PJ0p+KXPPmQQWyfXz6z/xIz40y3o364vASSSrquW3chPTPDj0wnkb6r8BnySa3UaRzjBrCtxYPDBK7dkZLQ2xmteJoyGSKm6wE5p6XJPPBoCJBtDfFtEDcPuJodDUTgRP/OorX0aLKGtBapnE1WLZdVEGr4e1hnaLvQ85G9qtWuiQ+QLD10ltNNl6U3UHEKjI9x3GeI2i0MABw7uZpJKfdlXPL++yPtJan7zj+8lR/adOdGUVzyMqVj0iFh9TfbsY9y+VkA0STfBiGE7OIGxCuN4vL24oyIFl4Jv4p/1Abr04LOfgytPv3406D0gxFYvhQJMeoZogpxc7JZ6wvmrkUlcZMB/5L/abht5xnKvDpjL/DAwaiTcV8ECjAylCPL71CL0FpjO0=
