swp_api_settings_list:
    path: /api/{version}/settings/
    defaults: { _controller: SettingsBundle:Settings:list, version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [GET]

swp_api_settings_revert:
    path: /api/{version}/settings/revert/{scope}
    defaults: { _controller: SettingsBundle:Settings:revert, version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [POST]

swp_api_settings_update:
    path: /api/{version}/settings/
    defaults: { _controller: SettingsBundle:Settings:update, version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [PATCH]

swp_api_settings_bulk_update:
    path: /api/{version}/settings/bulk/
    defaults: { _controller: SettingsBundle:Settings:bulk, version: "v2" }
    requirements:
        slug: .*
    options:
        expose: true
    methods: [PATCH]
