services:
    _defaults:
        public: true

    swp_rule.expression_language:
        class: Symfony\Component\ExpressionLanguage\ExpressionLanguage

    swp_rule.evaluator.rule:
        class: SWP\Component\Rule\Evaluator\RuleEvaluator
        public: true
        arguments:
            - '@logger'
            - '@swp_rule.expression_language'
        tags:
            - { name: monolog.logger, channel: swp_rule }

    swp_rule.applicator_chain:
        class: SWP\Component\Rule\Applicator\RuleApplicatorChain
        arguments:
            - {} # rule applicators array

    swp_rule.processor.rule:
        class: SWP\Component\Rule\Processor\RuleProcessor
        arguments:
            - '@swp.repository.rule'
            - '@swp_rule.evaluator.rule'
            - '@swp_rule.applicator_chain'
            - '@swp.repository.publish_destination'
