imports:
    - { resource: config_dev.yml }
    - { resource: parameters_test.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
    profiler:
        enabled: true
        collect: false

#doctrine:
#    dbal:
#        default_connection: default
#        connections:
#            default:
#                driver:   pdo_sqlite
#                path:     "%kernel.cache_dir%/test.db3"

liip_functional_test: ~

sylius_theme:
    sources:
        tenantable:
            directories:
                - "%kernel.root_dir%/../src/SWP/Bundle/WebRendererBundle/Tests/Fixtures/themes"

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

swp_content:
    persistence:
        phpcr:
            default_content_path: "articles"

oneup_flysystem:
    adapters:
        filesystem_adapter:
            local:
                directory: "%kernel.cache_dir%/uploads/"
