swp_templateengine:
    resource: "@SWPTemplateEngineBundle/Controller/"
    type:     annotation

swp_content:
    resource: "@SWPContentBundle/Controller/"
    type:     annotation

swp_webrenderer:
    resource: "@SWPWebRendererBundle/Controller/"
    type:     annotation

swp_updater:
    resource: "@SWPUpdaterBundle/Resources/config/routing.yml"

swp_bridge:
    resource: "@SWPBridgeBundle/Controller"
    type:     annotation
