services:
    _defaults:
        public: true

    # move it into an appropriate place (CoreBundle?)
    swp.serializer:
        class: SWP\Bridge\JMSSerializerBundle\JMSSerializer
        arguments:
            - "@jms_serializer"

    swp_bridge_bundle.serializer.package_subscriber:
        class: SWP\Bundle\BridgeBundle\Serializer\PackageSubscriber
        tags:
            - { name: jms_serializer.event_subscriber }

    swp_bridge_bundle.listener.validation:
        class: SWP\Bundle\BridgeBundle\EventListener\ValidationListener
        arguments:
            - '@validator'
        tags:
            - { name: kernel.event_listener, event: swp.validation, method: onValidation }

    swp_bridge_bundle.listener.validation_exception:
        class: SWP\Bundle\BridgeBundle\EventListener\ValidationExceptionListener
        arguments:
            - '@swp.serializer'
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    swp_bridge_bundle.object_constructor:
        class: SWP\Bundle\BridgeBundle\Serializer\ObjectConstructor
        public: false

    jms_serializer.object_constructor:
        alias: swp_bridge_bundle.object_constructor
        public: false
