SWP\Bundle\TemplatesSystemBundle\Model\Container:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        name:
            expose: true
            type: string
        type:
            expose: true
            type: integer
        visible:
            expose: true
            type: boolean
        width:
            expose: true
            type: integer
        height:
            expose: true
            type: integer
        styles:
            expose: true
            type: string
        cssClass:
            expose: true
            type: string
        data:
            expose: true
        widgets:
            expose: true
    relations:
        -
            rel: self
            href:
                route: swp_api_templates_get_container
                parameters:
                    id: expr(object.getId())
