SWP\Bundle\TemplateEngineBundle\Model\ContainerWidget:
    type: entity
    table: containers_widgets
    repositoryClass: SWP\Bundle\TemplateEngineBundle\Repository\ContainerWidgetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    uniqueConstraints:
        container_widget_idx:
            columns: [ container_id, widget_id ]
    fields:
        position:
            type: integer
            gedmo:
                - sortablePosition
    manyToOne:
        widget:
            targetEntity: SWP\Bundle\TemplateEngineBundle\Model\Widget
            inversedBy: containers
            joinColumn:
                name: widget_id
                referencedColumnName: id
        container:
            targetEntity: SWP\Bundle\TemplateEngineBundle\Model\Container
            inversedBy: widgets
            joinColumn:
                name: container_id
                referencedColumnName: id
            gedmo:
                - sortableGroup
