SWP\Bundle\TemplateEngineBundle\Model\Container:
    type: entity
    table: swp_container
    repositoryClass: SWP\Bundle\TemplateEngineBundle\Repository\ContainerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            length: 255
        type:
            type: integer
        width:
            type: integer
            nullable: true
        height:
            type: integer
            nullable: true
        styles:
            type: text
            nullable: true
        cssClass:
            type: string
            length: 255
            nullable: true
        visible:
            type: boolean
        createdAt:
            type: datetime
            options:
                default: "now"
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        name_idx:
          columns: [ name, tenant_id ]
    manyToOne:
        tenant:
            targetEntity: SWP\Bundle\WebRendererBundle\Model\Tenant
    oneToMany:
        data:
            targetEntity: SWP\Bundle\TemplateEngineBundle\Model\ContainerData
            mappedBy: container
        widgets:
            targetEntity: SWP\Bundle\TemplateEngineBundle\Model\ContainerWidget
            mappedBy: container
