SWP\Bundle\ContentBundle\Model\Article:
    exclusion_policy: ALL
    accessor_order: custom
    custom_accessor_order: [id,title,body,slug,publishedAt, status, route, isPublishable,metadata,lead,code,sources,extra,slideshows,previousRelativeUrls,createdAt,updatedAt,authors,keywords,media, templateName,publishStartDate,publishEndDate,featureMedia,seoMetadata]
    properties:
        id:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: integer
        title:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: string
        lead:
            expose: true
            groups: [api, api_articles_list]
            type: string
        body:
            expose: true
            groups: [api, api_articles_list]
            type: string
        slug:
            expose: true
            groups: [api, api_articles_list]
            type: string
        route:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
        publishedAt:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: DateTime
        status:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: string
        sources:
            expose: true
            groups: [api]
        templateName:
            expose: true
            groups: [api]
            type: string
        createdAt:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api, api_packages_list, api_articles_list]
            type: DateTime
        publishStartDate:
            expose: true
            groups: [api]
            type: DateTime
        publishEndDate:
            expose: true
            groups: [api]
            type: DateTime
        isPublishable:
            expose: true
            groups: [api]
            type: boolean
        media:
            expose: true
            groups: [api]
        featureMedia:
            expose: true
            groups: [api, api_articles_featuremedia]
        metadata:
            expose: true
            groups: [api]
            type: array
            accessor:
                getter: getMetadata
        keywords:
            expose: true
            groups: [api]
            type: ArrayCollection
        code:
            expose: true
            groups: [api]
            type: string
        authors:
            expose: true
            groups: [api, api_article_authors]
        slideshows:
            expose: true
            groups: [api, api_articles_slideshows]
            type: ArrayCollection
        seoMetadata:
            expose: true
            groups: [api, api_articles_seometadata]
        previousRelativeUrls:
            expose: true
            groups: [api]
    relations:
        -
            rel: self
            href:
                route: swp_api_content_show_articles
                parameters:
                    id: "expr(object.getSlug())"
        -
            rel: online
            href:
                route: "expr(object.getRoute() ? object.getRoute().getRouteName() : 'swp_api_content_list_articles')"
                parameters:
                    slug: "expr(object.getSlug())"
            exclusion:
                exclude_if: "expr(object.getRoute() !== null && object.getRoute().getType() !== 'collection')"
        -
            rel: online
            href:
                route: "expr(object.getRoute() ? object.getRoute().getRouteName() : 'swp_api_content_list_articles' )"
            exclusion:
                exclude_if: "expr(object.getRoute() !== null && object.getRoute().getType() !== 'content')"
        -
            rel: related
            href:
                route: swp_api_content_list_related_articles
                parameters:
                    id: "expr(object.getId())"
            exclusion:
                exclude_if: "expr(null === object.getId())"
    virtual_properties:
        getExtraArray:
            name: extra
            serialized_name: extra
            type: array