SWP\Bundle\ContentBundle\Model\Route:
    exclusion_policy: ALL
    properties:
        templateName:
            expose: true
            groups: [api]
        type:
            expose: true
            groups: [api, api_routes_list]
        name:
            expose: true
            groups: [api, api_routes_list, public_api]
        description:
            expose: true
            groups: [api]
        slug:
            expose: true
            groups: [api, api_routes_list, public_api]
        cacheTimeInSeconds:
            expose: true
            groups: [api]
            type: integer
        articlesTemplateName:
            expose: true
            groups: [api]
            type: string
        position:
            expose: true
            groups: [api]
            type: integer
        lft:
            expose: true
            groups: [api]
            type: integer
        rgt:
            expose: true
            groups: [api]
            type: integer
        level:
            expose: true
            groups: [api]
            type: integer
        children:
            expose: true
            groups: [api]
        parent:
            expose: true
            groups: [api]
            type: integer
            accessor:
                getter: getParentId
    relations:
        - rel: self
          href:
                route: swp_api_content_show_routes
                parameters:
                    id: expr(object.getId())
          exclusion:
              groups: [api]
        - rel: parent
          href:
                route: swp_api_content_show_routes
                parameters:
                    id: expr(object.getParent().getId())
          exclusion:
                exclude_if: expr(null === object.getParent())
                groups: [api]