SWP\Bundle\RedirectRouteBundle\Model\RedirectRoute:
    type:  mappedSuperclass
    table: swp_redirect_route
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        routeName:
            type: string
            nullable: true
        uri:
            type: string
            nullable: true
        permanent:
            type: boolean
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: true
    indexes:
        swp_redirect_route_prefix:
            columns: [staticPrefix]
