SWP\Component\Bridge\Model\Package:
    type: mappedSuperclass
    table: swp_package
    repositoryClass: SWP\Bundle\BridgeBundle\Doctrine\ORM\PackageRepository
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
        loggable: true
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        headline:
            type: string
        slugline:
            type: string
            nullable: true
        guid:
            type: string
        evolvedFrom:
            type: string
            nullable: true
        byline:
            type: string
            nullable: true
        language:
            type: string
        description:
            type: text
            nullable: true
        subjects:
            type: array
        services:
            type: array
            nullable: true
        keywords:
            type: array
        places:
            type: array
        type:
            type: string
        located:
            type: string
            nullable: true
        pubStatus:
            type: string
        urgency:
            type: integer
        priority:
            type: integer
        version:
            type: integer
        body:
            type: text
            nullable: true
        enabled:
            type: boolean
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    oneToMany:
        items:
            targetEntity: SWP\Component\Bridge\Model\ItemInterface
            cascade: ["persist"]
            mappedBy: package
