SWP\Bundle\CoreBundle\Model\Article:
    exclusion_policy: ALL
    properties:
        isPublishedFBIA:
            expose: true
            groups: [api, api_articles_list]
        tenantCode:
            serialized_name: tenant
            expose: true
            groups: [api, api_articles_list]
            type: SWP\Bundle\CoreBundle\Model\TenantInterface
        articleStatistics:
            expose: true
            groups: [api, api_articles_statistics_list]
        externalArticle:
            expose: true
            groups: [api]
        paywallSecured:
            expose: true
            groups: [api]
            type: boolean
        contentLists:
            expose: true
            groups: [api]
        commentsCount:
            expose: true
            groups: [api, api_articles_list]
            access_type: public_method
        isPublishedToAppleNews:
            expose: true
            groups: [api, api_articles_list]
    relations:
        -
            rel: slideshows
            href:
                route: swp_api_slideshows_list
                parameters:
                    articleId: "expr(object.getId())"
            exclusion:
                exclude_if: "expr(object.getId() === null)"
