SWP\Component\Bridge\Model\Author:
    exclusion_policy: ALL
    properties:
        name:
            type: string
        biography:
            type: string
        role:
            type: string
        avatarUrl:
            type: string
            serialized_name: avatar_url
            access_type: public_method
        jobTitle:
            serialized_name: jobtitle
            type: array
