SWP\Bundle\ContentBundle\Doctrine\ODM\PHPCR\Route:
    referenceable: true
    fields:
        templateName:
            type: string
            nullable: true
        articlesTemplateName:
            type: string
            nullable: true
        type:
            property: route_type
            type: string
        cacheTimeInSeconds:
            type: int
