SWP\Component\MultiTenancy\Model\Tenant:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            type: integer
        name:
            expose: true
            type: string
        enabled:
            expose: true
            type: boolean
        subdomain:
            expose: true
            type: string
        domainName:
            expose: true
            type: string
        code:
            expose: true
            type: string
        createdAt:
            expose: true
            type: DateTime
        updatedAt:
            expose: true
            type: DateTime
        organization:
            expose: true
            type: SWP\Component\MultiTenancy\Model\Organization
