SWP\Component\ContentList\Model\ContentListItem:
    exclusion_policy: ALL
    properties:
        id:
            expose: true
            groups: [api, api_content_list_item_details]
            type: integer
        position:
            expose: true
            groups: [api, api_content_list_item_details]
            type: integer
        content:
            expose: true
            groups: [api, api_content_list_item_details]
        enabled:
            expose: true
            groups: [api, api_content_list_item_details]
            type: boolean
        sticky:
            expose: true
            groups: [api, api_content_list_item_details]
            type: boolean
        createdAt:
            expose: true
            groups: [api, api_content_list_item_details]
            type: DateTime
        updatedAt:
            expose: true
            groups: [api, api_content_list_item_details]
            type: DateTime
