services:
    _defaults:
        public: true
        autoconfigure: true
        autowire: true

    SWP\Bundle\CoreBundle\Consumer\SendWebhookConsumer:
        arguments:
            - '@jms_serializer'
            - '@monolog.logger.swp_send_webhook'

    SWP\Bundle\CoreBundle\Consumer\ContentPushConsumer:
        arguments:
            - '@lock.factory'
            - '@monolog.logger.swp_content_push'
            - '@swp.repository.package'
            - '@event_dispatcher'
            - '@swp_bridge.transformer.json_to_package'
            - '@swp.object_manager.package'
            - '@swp_multi_tenancy.tenant_context'
            - '@Sentry\State\HubInterface'
            - '@SWP\Bundle\CoreBundle\Hydrator\PackageHydratorInterface'

    SWP\Bundle\CoreBundle\Consumer\ImageConversionConsumer:
        arguments:
            - '@jms_serializer'
            - '@monolog.logger.swp_image_conversion'
            - '@swp.repository.image_rendition'
