SWP\Bundle\CoreBundle\Model\Article:
    type: mappedSuperclass
    table: swp_article
    fields:
        tenantCode:
            type: string
        isPublishedFBIA:
            type: boolean
            nullable: true
        paywallSecured:
            type: boolean
            nullable: true
        commentsCount:
            type: integer
            nullable: true
        isPublishedToAppleNews:
            type: boolean
            options:
                default: false
    manyToOne:
        organization:
            targetEntity: SWP\Component\MultiTenancy\Model\OrganizationInterface
            joinColumn:
                name: organization_id
                referencedColumnName: id
        package:
            targetEntity: SWP\Component\Bridge\Model\PackageInterface
            inversedBy: articles
            joinColumn:
                name: package_id
                referencedColumnName: id
    oneToOne:
        articleStatistics:
            targetEntity: SWP\Bundle\AnalyticsBundle\Model\ArticleStatisticsInterface
            mappedBy: article
        externalArticle:
            targetEntity: SWP\Bundle\CoreBundle\Model\ExternalArticleInterface
            mappedBy: article
        appleNewsArticle:
            targetEntity: SWP\Bundle\CoreBundle\Model\AppleNewsArticleInterface
            mappedBy: article
    uniqueConstraints:
        swp_article_slug_not_null_deleted_at_idx:
            columns: [ slug, tenant_code, organization_id, deleted_at ]
            options:
                where: "deleted_at IS NOT NULL"
        swp_article_slug_null_deleted_at_idx:
            columns: [ slug, tenant_code, organization_id ]
            options:
                where: "deleted_at IS NULL"
    indexes:
        swp_status_route:
            columns: [status, route_id]
        swp_deleted_tenant:
            columns: [deleted_at, tenant_code]
        swp_status_deleted_route_tenant:
            columns: [status, tenant_code, deleted_at, route_id]
        swp_deleted_at:
            columns: [deleted_at]
        swp_article_published_at:
            columns: [published_at]
        swp_count_route:
            columns: [deleted_at, status, tenant_code]
