SWP\Bundle\CoreBundle\Model\MenuItem:
    type: entity
    table: swp_menu
    fields:
        tenantCode:
            type: string
    manyToOne:
        route:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\Route
            joinColumn:
                name: route_id
                referencedColumnName: id
