SWP\Bundle\CoreBundle\Model\Tenant:
    type: entity
    table: swp_tenant
    fields:
        themeName:
            type: string
            nullable: true
        ampEnabled:
            type: boolean
    oneToOne:
        homepage:
            targetEntity: SWP\Bundle\ContentBundle\Model\RouteInterface
            fetch: EAGER
            joinColumn:
                name: tenant_route_id
                referencedColumnName: id
                nullable: true
        outputChannel:
            targetEntity: SWP\Component\OutputChannel\Model\OutputChannelInterface
            fetch: EAGER
            cascade: ['persist', 'remove']
            mappedBy: tenant
        appleNewsConfig:
            targetEntity: SWP\Bundle\CoreBundle\Model\AppleNewsConfig
            cascade: ['persist', 'remove']
            mappedBy: tenant