SWP\Bundle\CoreBundle\Model\Tenant:
    type: entity
    table: swp_tenant
    fields:
        themeName:
            type: string
            nullable: true
        domainName:
            type: string
            nullable: true
    oneToOne:
        homepage:
            targetEntity: SWP\Bundle\ContentBundle\Doctrine\ORM\Route
            joinColumn:
                name: tenant_route_id
                referencedColumnName: id
                nullable: true
